// Objective-C API for talking to golang.org/x/mobile/example/bind/hello Go package.
//   gobind -lang=objc golang.org/x/mobile/example/bind/hello
//
// File is generated by gobind. Do not edit.

#ifndef __Hello_H__
#define __Hello_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* HelloGreetings(NSString* name);

#endif
