// Objective-C API for talking to github.com/bytom-community/mobile/sdk Go package.
//   gobind -lang=objc github.com/bytom-community/mobile/sdk
//
// File is generated by gobind. Do not edit.

#ifndef __Wallet_H__
#define __Wallet_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* WalletBackupWallet(void);

FOUNDATION_EXPORT NSString* WalletCreateAccount(NSString* alias, long quorum, NSString* rootXPub);

FOUNDATION_EXPORT NSString* WalletCreateAccountReceiver(NSString* accountID, NSString* accountAlias);

FOUNDATION_EXPORT NSString* WalletCreateKey(NSString* alias, NSString* password);

FOUNDATION_EXPORT void WalletInitWallet(NSString* storagePath);

FOUNDATION_EXPORT NSString* WalletListAccounts(void);

FOUNDATION_EXPORT NSString* WalletListAddress(NSString* accountID, NSString* accountAlias);

FOUNDATION_EXPORT NSString* WalletListKey(void);

FOUNDATION_EXPORT NSString* WalletResetKeyPassword(NSString* rootXPub, NSString* oldPassword, NSString* newPassword);

FOUNDATION_EXPORT NSString* WalletRestoreWallet(NSString* walletImage);

FOUNDATION_EXPORT NSString* WalletSignTransaction(NSString* transaction, NSString* password);

#endif
