// Objective-C API for talking to github.com/bytom-community/mobile/wallet Go package.
//   gobind -lang=objc github.com/bytom-community/mobile/wallet
//
// File is generated by gobind. Do not edit.

#ifndef __Wallet_H__
#define __Wallet_H__

@import Foundation;
#include "Universe.objc.h"


@class WalletAPI;
@class WalletCheckPasswordResp;
@class WalletResetPasswordResp;
@class WalletResponse;

/**
 * API is the scheduling center for server
 */
@interface WalletAPI : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field API.Hsm with unsupported type: *github.com/bytom-community/mobile/wallet/pseudohsm.HSM

// skipped method API.PseudohsmCreateKey with unsupported parameter or return types

@end

/**
 * CheckPasswordResp is response for check key password
 */
@interface WalletCheckPasswordResp : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (BOOL)checkResult;
- (void)setCheckResult:(BOOL)v;
@end

/**
 * ResetPasswordResp is response for reset key password
 */
@interface WalletResetPasswordResp : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (BOOL)changed;
- (void)setChanged:(BOOL)v;
@end

/**
 * Response describes the response standard.
 */
@interface WalletResponse : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)status;
- (void)setStatus:(NSString*)v;
- (NSString*)code;
- (void)setCode:(NSString*)v;
- (NSString*)msg;
- (void)setMsg:(NSString*)v;
- (NSString*)errorDetail;
- (void)setErrorDetail:(NSString*)v;
// skipped field Response.Data with unsupported type: interface{}

@end

/**
 * FAIL indicated the rpc calling is failed.
 */
FOUNDATION_EXPORT NSString* const WalletFAIL;
/**
 * SUCCESS indicates the rpc calling is successful.
 */
FOUNDATION_EXPORT NSString* const WalletSUCCESS;

@interface Wallet : NSObject
/**
 * ErrDefault is default Bytom API Error
 */
+ (NSError*) errDefault;
+ (void) setErrDefault:(NSError*)v;

@end

FOUNDATION_EXPORT NSString* WalletCreateWallet(NSString* keystorePath, NSString* alias, NSString* password);

// skipped function FormatErrResp with unsupported parameter or return types


// skipped function NewErrorResponse with unsupported parameter or return types


// skipped function NewSuccessResponse with unsupported parameter or return types


#endif
